version: '3'
services:
  openssh:
  # prebuild image
  image: ghcr.io/vibrantleaf/container-opensshd:nightly
  #
  #  optionaly build locally
  # build: ./Containerfile
  volumes:
  # mount a local sshd_config to the contianer
    - './sshd_config:/etc/ssh/sshd_config:ro'
  ports:
    # we must pass the sshd port though to the contianer
    - 22:22


